export const roles = {
  STUDENT: "STUDENT",
  QA_COORDINATOR: "MARKETING COORDINATOR",
  QA_MANAGER: "MARKETING MANAGER",
  ADMIN: "Admin",
  ALL: ["STUDENT", "MARKETING COORDINATOR", "MARKETING MANAGER", "Admin"]
};
